### PR TITLE
Error checking in .py

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vBm** [comment]
We're using 4 spaces for indentation, so please don't mix tabs and spaces for starters.

After you fix that, you should squash everything into one commit and use "Add error checking in .py" or something similar as commit message (update mpc.hc.np.py means nothing)

**Comment by XhmikosR** [comment]
Shouldn't we return something else when the exception occurs?

And please squash and use spaces as @vBm says above, thanks.

**Comment by vBm** [comment]
Maybe something along the lines "Error: We couldn't make a connection to MPC-HC's webui, make sure it's enabled"

**Comment by XhmikosR** [comment]
Deleted user...

**Comment by TheRealBanana** [comment]
https://gist.github.com/TheRealBanana/3cf1107030ceb126e700

**Pull request closed without merging**
